name: Upload Python Package

on:
  release:
    types: [edited, created, published]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]
        python-version: [3.9]
        include:
          - os: windows-2022
            compiler: "msvc"
          - os: ubuntu-22.04
            compiler: "gcc"
          - os: macos-12
            compiler: "gcc"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true
          ninja: true
          vcpkg: true
          cppcheck: true
          clangtidy: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build a binary wheel and a source tarball
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
